#!/usr/bin/env bash

function notify-restart {
    user_name=$(loginctl list-users -j | jq -r '.[] | select(.state == "active") | select(.uid > 0) | .user')
    run0 -u "$user_name" notify-send \
    --app-name="System Updates" \
    --app-icon="org.gnome.Settings-system-symbolic" \
    --icon="software-update-available-symbolic" \
    --transient \
    --urgency=normal \
    "Updates Ready to Install" \
    "System updates will be installed on next restart"
}

if bootc upgrade --check | grep -qF "Update available"; then
    bootc upgrade --quiet
    if [ $? -eq 0 ]; then
        notify-restart
    else
        exit 1
    fi
fi
