# forge.fedoraproject.org/atomic-desktops/config/pulls/755
omit_dracutmodules+=" fips fips-crypto-policies lunmask memstrack modsign nss-softokn "

# no crypt support for now
# forge.fedoraproject.org/atomic-desktops/config/src/branch/main/initramfs.yaml
omit_dracutmodules+=" systemd-cryptsetup crypt tpm2-tss systemd-pcrphase "

omit_dracutmodules+=" clevis clevis-pin-null clevis-pin-sss clevis-pin-tang clevis-pin-tpm2 "
omit_dracutmodules+=" qemu qemu-net "
