name: build image and push to github’s container registry

on:
  workflow_call:
    inputs:
      image-tag:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-26.04
    steps:
      - name: build
        run: |
          IMAGE_NAME="ghcr.io/lfchr/linux:${{ inputs.image-tag }}" \
          make image

      - name: push
        run: podman push ghcr.io/lfchr/linux:${{ inputs.image-tag }}
