name: clean ghcr

on: workflow_dispatch

jobs:
  clean:
    runs-on: ubuntu-26.04
    steps:
      - name: login
        run: |
          skopeo login ghcr.io \
          -u ${{ github.actor }} \
          -p ${{ secrets.GITHUB_TOKEN }}

      - name: get digests
        run: |
          digests=$( \
            curl -L \
              -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
              -H "Accept: application/vnd.github+json" \
              -H "X-GitHub-Api-Version: 2026-03-10" \
              https://api.github.com/user/packages/container/linux/versions?per_page=100 \
            | jq -r 'sort_by(.updated_at) | .[0:-8].[].name' \
            | tr '\n' ' ' \
          )
          echo "digests=$digests" >> "$GITHUB_ENV"

      - name: clean
        run: |
          for digest in $digests; do \
            skopeo delete docker://ghcr.io/${{ github.repository }}@$digest; \
          done
          

