name: clean ghcr

on: workflow_dispatch

jobs:
  clean:
    runs-on: ubuntu-26.04
    steps:
      - name: get digests
        run: |
          version_ids=$( \
            curl -L \
              -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
              -H "Accept: application/vnd.github+json" \
              -H "X-GitHub-Api-Version: 2026-03-10" \
              https://api.github.com/user/packages/container/linux/versions?per_page=100 \
            | jq -r 'sort_by(.updated_at) | .[0:-8].[].id' \
            | tr '\n' ' ' \
          )
          echo "version_ids=$version_ids" >> "$GITHUB_ENV"

      - name: clean
        run: |
          for id in $version_ids; do \
            curl -L \
              -X DELETE \
              -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
              -H "Accept: application/vnd.github+json" \
              -H "X-GitHub-Api-Version: 2026-03-10" \
              https://api.github.com/user/packages/container/linux/versions/$id; \
          done
          

