name: build latest

on:
  push:
    tags: 
      - latest

jobs:
  build-push:
    uses: ./.github/workflows/build-push-ghcr.yml@main
    with:
      image-repo: ${{ github.repository }}
      image-tag: latest
      ghcr-user: ${{ github.actor }}
    secrets:
      ghcr_token: ${{ secrets.GITHUB_TOKEN }}
