name: build testing

on:
  push:
    tags: 
      - tesing

jobs:
  build-push:
    uses: ./.github/workflows/build-push-ghcr.yml@main
    with:
      image-repo: ${{ github.repository }}
      image-tag: testing
      ghcr-user: ${{ github.actor }}
      ghcr_token: ${{ secrets.GITHUB_TOKEN }}
